# Generated by Django 3.2.1 on 2021-05-05 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, validators=[
                    django.core.validators.RegexValidator(message='Allowed characters: "a-z", "0-9", "_"',
                                                          regex='^[a-z0-9_]*$')])),
                ('name', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
